### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by thiagofigueiro** [dubirajara/omdbapi#139]
Hi!  I know the readme specifically says this project requires Python 3.7 but is there any chance you'd support Python 3.6?

**Comment by dubirajara** [comment]
Hi @thiagofigueiro , do you have any problem in using python 3.7? Can you give me reasons for not using the latest version of python? just to evaluate portability and know the reasons.

Thank you

**Comment by thiagofigueiro** [comment]
At home there's nothing - I believe - stopping me from using 3.7. At work I've had incompatibilities with it and so have decided to wait it out on 3.6 a little longer.

I've rolled back omdbapi to 0.5.1 as the breaking change (dataclass) was introduced on 0.5.2. I'd offer to send a PR to add backwards compatibility but I'm not sure what your other 3.7 plans are for this project so I'm happy to stick with 0.5.1.

Thanks for the quick reply! feel free to close this issue.

**Comment by dubirajara** [comment]
Thanks @thiagofigueiro  , as you say, the only thing that breaks the imcompatibility is dataclass, I have my reasons for using it, it is a feature of 3.7 that I like a lot.
Omdbapi is a simple wrapper of the Open Movie Database, I do not intend to continue developing more features, although I am open to new ideas and PR. So I'll keep version 0.5.3 as it is, and update the "readme" for anyone who wants to use with python 3.6 must install version 0.5.1.

Thank you
